apiVersion: v1
kind: ConfigMap
metadata:
  name: jungle-events-config
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SERVER_PORT: "8090"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
