pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'JDK-17'
    }

    environment {
        IMAGE_NAME    = "salmaachour93/jungle-payments"
        IMAGE_TAG     = "${BUILD_NUMBER}"
        SONAR_PROJECT = "jungle-payments"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Unit Tests') {
            steps {
                dir('jungle-payments') {
                    sh 'mvn test jacoco:report'
                }
            }
            post {
                always {
                    junit 'jungle-payments/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Build JAR') {
            steps {
                dir('jungle-payments') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    dir('jungle-payments') {
                        sh """
                            mvn sonar:sonar \
                              -Dsonar.projectKey=${SONAR_PROJECT} \
                              -Dsonar.projectName='Jungle Payments'
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: false
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('jungle-payments') {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -t ${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
                    sh "docker push ${IMAGE_NAME}:latest"
                    sh 'docker logout'
                }
            }
        }
    }

    post {
        success {
            echo "CI jungle-payments réussi — image ${IMAGE_NAME}:${IMAGE_TAG} publiée"
        }
        failure {
            echo "CI jungle-payments échoué — vérifier les logs"
        }
        always {
            sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true"
        }
    }
}
