spring.application.name=jungle-payments
server.port=8091

# Base de données dédiée payments
spring.datasource.url=jdbc:mysql://localhost:3306/jungle_payments_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Stripe TEST keys (récupérées sur https://dashboard.stripe.com/test/apikeys)
stripe.secret-key=sk_test_51TIrptDFtDXObNlbH1PpADDFEZZWofZof0Cu3r28AL32QQqhI9RDSqjbGAZi3QzOIqIJVf0wYd0ebpPSLFJN5tWa00L8JKxUsD
stripe.publishable-key=pk_test_51TIrptDFtDXObNlbkZqLN0wMMNxC3jUnpeRurWHGBO67HqiCsYXXtbGVUxpWv4eTy36G7MIxRuLlroe7a243AV6k00Hoomykv7

#lien mta3 stripe tests des cartes
#https://docs.stripe.com/testing#cards
# Swagger
# http://localhost:8091/swagger-ui/index.html