apiVersion: apps/v1
kind: Deployment
metadata:
  name: jungle-payments
  labels:
    app: jungle-payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jungle-payments
  template:
    metadata:
      labels:
        app: jungle-payments
    spec:
      containers:
        - name: jungle-payments
          image: salmaachour93/jungle-payments:latest
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: jungle-payments-secret
                  key: db-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: jungle-payments-secret
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jungle-payments-secret
                  key: db-password
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jungle-payments-secret
                  key: stripe-key
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: MANAGEMENT_HEALTH_EUREKA_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: jungle-payments
spec:
  selector:
    app: jungle-payments
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP
