apiVersion: v1
kind: Secret
metadata:
  name: jungle-payments-secret
type: Opaque
stringData:
  db-url: jdbc:mysql://mysql-service:3306/jungle_payments?useSSL=false&allowPublicKeyRetrieval=true
  db-username: root
  db-password: root
  stripe-key: sk_test_your_stripe_key_here
